name: Train 0.2 subset PLM-ICD Hyperparameter Sweep
program: main.py
method: random
metric:
  name: val.all.f1_micro_tuned
  goal: maximize
parameters:
  experiment:
    value: mimiciii_clean/plm_icd
  metrics:
    value: no_auc
  optimizer:
    value: adamw
  lr_scheduler:
    value: warmup_linear_decay
  trainer.epochs:
    value: 20
  trainer.threshold_tuning:
    value: true
  trainer.validate_on_training_data:
    value: false
  data.max_length:
    value: 4000
  callbacks:
    value: sweep
  optimizer.configs.lr:
    values: [1e-5, 5e-5, 1e-4]
  optimizer.configs.weight_decay:
    values: [0, 1e-5, 1e-4, 1e-3]
  dataloader.batch_size:
    values: [8, 16, 32]
  data.split_filename:
    value: mimiciii_clean_subsplit_0.2.feather

  

command:
  - ${env}
  - python
  - ${program}
  - gpu=-1
  - ${args_no_hyphens}
