name: Ablation Study - Max Length
program: main.py
method: grid
metric:
  name: val.all.f1_micro_tuned
  goal: maximize
parameters:
  experiment:
    values: 
      - mimiciii_clean/vanillaconv
      - mimiciii_clean/vanillagru
      - mimiciii_clean/caml
      - mimiciii_clean/laat
      - mimiciii_clean/multi_res_conv
      - mimiciii_clean/plm_icd
  data.max_length:
    value: 2500
  dataset.configs.max_length_tokens: 
    value: 20000
    


command:
  - ${env}
  - python
  - ${program}
  - gpu=-1
  - ${args_no_hyphens}
