name: Reproducibility Experiment
program: main.py
method: grid
metric:
  name: val.all.f1_micro
  goal: maximize
parameters:
  metrics:
    value: reproducibility 
  experiment:
    values: 
      - mimiciii_50/vanillaconv
      - mimiciii_50/vanillagru
      - mimiciii_50/caml
      - mimiciii_50/laat
      - mimiciii_50/multi_res_conv
      - mimiciii_50/plm_icd
      - mimiciii_full/vanillaconv
      - mimiciii_full/vanillagru
      - mimiciii_full/caml
      - mimiciii_full/laat
      - mimiciii_full/multi_res_conv
      - mimiciii_full/plm_icd

command:
  - ${env}
  - python
  - ${program}
  - gpu=-1
  - ${args_no_hyphens}
